### ISSUE TITLE
Contact pls, regarding grpc-zerolog repo

### ISSUE THREAD

**Issue by christianschmizz** [philip-bui/as-you-type-formatter#1]
Hi @philip-bui , 
I did not find any contact information, so I file this issue. Please excuse. Maybe you contact me via mail at schmizz.com or right in this issue ;)

I just noticed that the https://github.com/philip-bui/grpc-zerolog project is gone, which I am using for one my projects. Is there any reason for this or even better a new repo location?

Best regards
Christian

**Comment by philip-bui** [comment]
Hi @tc77 ,

Thanks for raising the issue to me, I was not aware of anyone using that library. The repository is now back up again, apologies for any issues or disruptions occurred and all the best with your project :).

Regards,
Philip
